name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm run clean
          npm run build:three
          npm run build:cjs
          npm run build:esm
          npm run build:webpack
      - name: Quality
        run: |
          npm run lint
      - name: Documentation
        run: |
          npm run build:typedoc
      - name: Test
        run: |
          npm run test:jenkins