name: Build JOSS Paper

on:
    push:
        paths:
            - './docs/paper/**'
    pull_request:
        paths:
            - './docs/paper/**'
    workflow_dispatch:

jobs:
    build-paper:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Set up Docker
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            # Start the Docker container using docker-compose
            - name: Build and run paper container
              run: docker-compose -f ./docs/paper/docker-compose.yml up --build --abort-on-container-exit

            # Upload the generated PDF as an artifact
            - name: Upload paper PDF
              uses: actions/upload-artifact@v3
              with:
                name: paper-pdf
                path: ./docs/paper/paper/paper.pdf